/* transaction不是一个component，而是一个临时的数据对象，所以需要继承uvm_sequence_item
class xxx_transaction extends uvm_sequence_item;

    // 1. 数据字段
    rand ...;

    // 2. register
    `uvm_object_utils_begin(...)
        ...
    `uvm_object_utils_end

    // 3. new
    function new(string name = "...");
        super.new(name);
    endfunction

endclass*/

class apb_transaction extends uvm_sequence_item;

    // request fields: generated by sequence and driven by driver
    rand bit        write;
    rand bit [31:0] addr;
    rand bit [31:0] wdata;
    rand bit [3:0]  strb;
    rand bit [2:0]  prot;

    // response fields: collected from DUT
    bit [31:0] rdata;
    bit       slverr;

    // macro：factory registration and field automation
    `uvm_object_utils_begin(apb_transaction)
        `uvm_field_int(write, UVM_DEFAULT)// write 参与自动打印、复制和比较
        `uvm_field_int(addr, UVM_HEX)// addr 参与自动化，并以十六进制显示
        `uvm_field_int(wdata, UVM_HEX)//写数据以十六进制显示
        `uvm_field_int(strb, UVM_BIN)//字节使能以二进制显示
        `uvm_field_int(prot, UVM_BIN)//保护属性按位查看更直观
        `uvm_field_int(rdata, UVM_HEX)//读数据以十六进制显示
        `uvm_field_int(slverr, UVM_DEFAULT)//设备错误默认显示
    `uvm_object_utils_end

    function new (string name = "apb_transaction");//初始化对象
        super.new(name);//初始化父类uvm_sequence_item 
    endfunction

endclass